COMMENT ON TABLE public.aceptacion IS 'Registro de aceptación de diagnósticos por paciente dentro del flujo clínico.';
COMMENT ON TABLE public.agent_memory IS 'Memoria conversacional persistida por sesión para el agente principal.';
COMMENT ON TABLE public.agent_memory_interno IS 'Memoria interna de apoyo por sesión usada por procesos auxiliares del agente.';
COMMENT ON TABLE public.aplicaciones_cliente IS 'Aplicaciones o licencias asociadas a una empresa cliente.';
COMMENT ON TABLE public.aplicaciones_dispositivos IS 'Vinculación de dispositivos e IPs a aplicaciones de cliente.';
COMMENT ON TABLE public.artifact_stars IS 'Marcadores o favoritos de usuarios sobre artifacts.';
COMMENT ON TABLE public.artifact_versions IS 'Historial versionado del contenido de cada artifact.';
COMMENT ON TABLE public.artifacts IS 'Artefactos generados por usuarios o por conversaciones de chat.';
COMMENT ON TABLE public.auditoria_historial IS 'Bitácora genérica de cambios a nivel tabla, columna y fila.';
COMMENT ON TABLE public.dau_tracked_users IS 'Usuarios externos monitoreados para analítica DAU o redes sociales.';
COMMENT ON TABLE public.dau_user_tweets IS 'Tweets asociados a usuarios monitoreados para seguimiento analítico.';
COMMENT ON TABLE public.diagnostico IS 'Diagnósticos clínicos asociados a pacientes.';
COMMENT ON TABLE public.drive_files IS 'Índice de archivos provenientes de Google Drive vinculados a contactos o empresas.';
COMMENT ON TABLE public.evaluaciones IS 'Evaluaciones de desempeño o calidad vinculadas a agentes y empresas.';
COMMENT ON TABLE public.metricas IS 'Métricas de negocio o rendimiento almacenadas por fecha y empresa.';
COMMENT ON TABLE public.minijuegos_jugadores IS 'Jugadores del sistema de minijuegos o gamificación por organización y empresa.';
COMMENT ON TABLE public.minijuegos_organizaciones IS 'Organizaciones o grupos base para dinámicas de minijuegos.';
COMMENT ON TABLE public.monica_memories IS 'Memorias semánticas almacenadas para Monica AI.';
COMMENT ON TABLE public.monica_user_profile IS 'Perfil estructurado de usuario para personalización de Monica AI.';
COMMENT ON TABLE public.n8n_chat_histories IS 'Historial conversacional persistido por flujos integrados con n8n.';
COMMENT ON TABLE public.pacientes IS 'Pacientes de empresas con datos personales e historia médica.';
COMMENT ON TABLE public.redaccion IS 'Documentos o piezas de redacción asociadas a tipos y contactos.';
COMMENT ON TABLE public.redaccion_detalle_historial IS 'Historial de cambios por sección o detalle de una redacción.';
COMMENT ON TABLE public.redaccion_detalles IS 'Secciones, partes o bloques ordenados de una redacción.';
COMMENT ON TABLE public.redaccion_tipos IS 'Plantillas o tipos de redacción configurables por empresa.';
COMMENT ON TABLE public.reporte_preliminar IS 'Captura preliminar de datos crudos por teléfono para reportes rápidos.';
COMMENT ON TABLE public.shortened_links IS 'Enlaces acortados con redirección, estado y contador de clics.';
COMMENT ON TABLE public.sintetico_ejecuciones IS 'Ejecuciones de pruebas sintéticas por perfil y escenario.';
COMMENT ON TABLE public.sintetico_escenarios IS 'Escenarios de prueba sintética asociados a empresa, agente y número.';
COMMENT ON TABLE public.sintetico_perfiles IS 'Perfiles sintéticos con personalidad para simulaciones automatizadas.';
COMMENT ON TABLE public.system_actions IS 'Catálogo maestro de acciones permitidas dentro del sistema de permisos.';
COMMENT ON TABLE public.system_modules IS 'Catálogo maestro de módulos funcionales del sistema.';
COMMENT ON TABLE public.system_permissions IS 'Permisos por rol y módulo con acciones serializadas en JSON.';
COMMENT ON TABLE public.system_roles IS 'Roles del sistema por empresa para control de acceso y permisos.';
COMMENT ON TABLE public.system_users IS 'Usuarios del sistema vinculados a auth, empresa, rol y miembro humano.';
COMMENT ON TABLE public.team_groups IS 'Grupos organizativos dinámicos del equipo humano por empresa.';
COMMENT ON TABLE public.team_invitations IS 'Invitaciones de acceso para miembros de equipo basadas en token.';
COMMENT ON TABLE public.temp_contactos_sin_citas IS 'Vista o tabla temporal de contactos sin citas para análisis operativo.';
COMMENT ON TABLE public.test_escritura IS 'Registros de pruebas de escritura o transformación de texto.';
COMMENT ON TABLE public.test_respuestas_agente_evaluador IS 'Resultados de pruebas donde un evaluador revisa respuestas de agentes.';
COMMENT ON TABLE public.training_courses IS 'Cursos de entrenamiento o academia interna por empresa.';
COMMENT ON TABLE public.training_lessons IS 'Lecciones ordenadas pertenecientes a cursos de entrenamiento.';
COMMENT ON TABLE public.training_questions IS 'Preguntas de evaluación asociadas a lecciones de entrenamiento.';
COMMENT ON TABLE public.training_streaks IS 'Rachas de actividad y constancia de aprendizaje por miembro del equipo.';
COMMENT ON TABLE public.training_user_progress IS 'Progreso individual de usuarios sobre lecciones de entrenamiento.';
COMMENT ON TABLE public.transcripciones IS 'Transcripciones y resúmenes de reuniones o citas sincronizadas.';
COMMENT ON TABLE public.usuarios_consentimientos IS 'Consentimientos clínicos y legales aceptados por usuarios o pacientes.';
COMMENT ON TABLE public.wp_actividades_log IS 'Log centralizado de actividades del sistema, agentes, contactos y usuarios.';
COMMENT ON TABLE public.wp_agente_roles IS 'Roles funcionales o perfiles base para agentes de IA.';
COMMENT ON TABLE public.wp_agente_tools IS 'Asignación de herramientas MCP o capacidades a agentes específicos.';
COMMENT ON TABLE public.wp_agentes IS 'Configuración principal de agentes de IA por empresa.';
COMMENT ON TABLE public.wp_auditoria IS 'Auditoría funcional de cambios en registros de la aplicación.';
COMMENT ON TABLE public.wp_citas IS 'Agenda de citas y eventos entre contactos, equipo y empresa.';
COMMENT ON TABLE public.wp_contacto_estado_embudo IS 'Estado actual e historial inmediato de embudo por contacto.';
COMMENT ON TABLE public.wp_contacto_team_asignaciones IS 'Asignaciones de contactos a miembros del equipo con rol operativo.';
COMMENT ON TABLE public.wp_contactos IS 'Tabla central del CRM para leads, prospectos y clientes.';
COMMENT ON TABLE public.wp_contactos_auditoria IS 'Auditoría de cambios y acciones relevantes sobre contactos.';
COMMENT ON TABLE public.wp_contactos_merge_log IS 'Bitácora de fusiones de contactos duplicados con snapshot y decisiones.';
COMMENT ON TABLE public.wp_contactos_nota IS 'Notas internas asociadas a contactos, visibles para equipo e IA.';
COMMENT ON TABLE public.wp_conversaciones IS 'Conversaciones entre contactos y agentes por canal y empresa.';
COMMENT ON TABLE public.wp_crm_pagos IS 'Pagos registrados dentro del módulo CRM financiero.';
COMMENT ON TABLE public.wp_crm_servicios IS 'Servicios vendidos o gestionados para contactos dentro del CRM.';
COMMENT ON TABLE public.wp_deep_research IS 'Trabajos de investigación profunda y sus resultados estructurados.';
COMMENT ON TABLE public.wp_documentacion IS 'Inventario de documentación interna de tablas, tools, conceptos y flujos.';
COMMENT ON TABLE public.wp_email_campanas IS 'Campañas de email marketing definidas por empresa.';
COMMENT ON TABLE public.wp_email_contacto_campana IS 'Inscripción y estado de cada contacto dentro de una campaña de email.';
COMMENT ON TABLE public.wp_email_envio IS 'Historial de envíos individuales de email por campaña y contacto.';
COMMENT ON TABLE public.wp_email_recibido IS 'Correos recibidos y asociados a contactos dentro de la empresa.';
COMMENT ON TABLE public.wp_empresa_ads_config IS 'Configuraciones de conectores publicitarios y métricas activas por empresa.';
COMMENT ON TABLE public.wp_empresa_embudo IS 'Etapas del embudo comercial configuradas por empresa.';
COMMENT ON TABLE public.wp_empresa_historial IS 'Historial de cambios sobre la configuración y datos de empresa.';
COMMENT ON TABLE public.wp_empresa_perfil IS 'Perfil maestro de empresa dentro de la arquitectura multi-tenant.';
COMMENT ON TABLE public.wp_error_logs IS 'Registro centralizado de errores de funciones y procesos del sistema.';
COMMENT ON TABLE public.wp_etiquetas_equipo IS 'Etiquetas reutilizables del equipo para tareas y organización interna.';
COMMENT ON TABLE public.wp_evaluacion_preliminar IS 'Evaluación preliminar de contactos con criterios, evidencia y oportunidades.';
COMMENT ON TABLE public.wp_facturas IS 'Facturación emitida a contactos por servicios y pagos.';
COMMENT ON TABLE public.wp_finanzas IS 'Movimientos financieros generales de ingresos, egresos y estados.';
COMMENT ON TABLE public.wp_follow_up IS 'Registro simple de mensajes o intentos de seguimiento.';
COMMENT ON TABLE public.wp_marketing_audiencia_contacto IS 'Relación entre audiencias de marketing y contactos miembros.';
COMMENT ON TABLE public.wp_marketing_audiencias IS 'Audiencias de marketing estáticas o dinámicas por empresa.';
COMMENT ON TABLE public.wp_mcp_tools_catalog IS 'Catálogo de herramientas MCP disponibles para agentes o empresas.';
COMMENT ON TABLE public.wp_mensajes IS 'Mensajes individuales pertenecientes a conversaciones del CRM.';
COMMENT ON TABLE public.wp_metodos_pago IS 'Catálogo de métodos de pago habilitados por empresa.';
COMMENT ON TABLE public.wp_module_usage_daily IS 'Agregados diarios de uso de módulos por empresa.';
COMMENT ON TABLE public.wp_multimedia IS 'Archivos multimedia asociados a contactos, contenidos o secciones.';
COMMENT ON TABLE public.wp_notificaciones IS 'Notificaciones simples orientadas a contactos o miembros del equipo.';
COMMENT ON TABLE public.wp_notificaciones_team IS 'Bandeja de notificaciones operativas para el equipo humano.';
COMMENT ON TABLE public.wp_numeros IS 'Números, canales o endpoints de comunicación por empresa y agente.';
COMMENT ON TABLE public.wp_numeros_horarios IS 'Configuración horaria de activación y desactivación por número.';
COMMENT ON TABLE public.wp_plan_consumo IS 'Consumo de características del plan de suscripción por empresa.';
COMMENT ON TABLE public.wp_planes_caracteristicas IS 'Características incluidas en cada plan de suscripción.';
COMMENT ON TABLE public.wp_planes_suscripcion IS 'Catálogo de planes de suscripción comercializados por la plataforma.';
COMMENT ON TABLE public.wp_proyectos IS 'Proyectos internos o de cliente vinculados a contactos y servicios.';
COMMENT ON TABLE public.wp_proyectos_costos IS 'Costos registrados dentro de proyectos, tareas o categorías operativas.';
COMMENT ON TABLE public.wp_recordatorios IS 'Recordatorios vinculados a contactos y conversaciones.';
COMMENT ON TABLE public.wp_suscripcion_historial IS 'Historial de cambios de plan o precio en suscripciones.';
COMMENT ON TABLE public.wp_suscripciones IS 'Suscripciones activas o históricas de empresas y contactos.';
COMMENT ON TABLE public.wp_system_alerts IS 'Alertas del sistema por severidad, contexto y empresa.';
COMMENT ON TABLE public.wp_tareas IS 'Tareas operativas asociadas a CRM, proyectos y equipo.';
COMMENT ON TABLE public.wp_tareas_asignados IS 'Relación muchos a muchos entre tareas y miembros asignados.';
COMMENT ON TABLE public.wp_tareas_comentarios IS 'Comentarios y menciones sobre tareas.';
COMMENT ON TABLE public.wp_tareas_etiquetas IS 'Relación entre tareas y etiquetas del equipo.';
COMMENT ON TABLE public.wp_tareas_historial IS 'Historial de acciones y cambios realizados sobre tareas.';
COMMENT ON TABLE public.wp_tareas_items IS 'Checklist o subtareas pertenecientes a una tarea.';
COMMENT ON TABLE public.wp_tareas_media IS 'Archivos multimedia adjuntos a tareas.';
COMMENT ON TABLE public.wp_tareas_reacciones IS 'Reacciones emoji sobre comentarios de tareas.';
COMMENT ON TABLE public.wp_team_humano IS 'Miembros humanos de una empresa con rol operativo, disponibilidad e integraciones.';
COMMENT ON TABLE public.wp_team_invitations IS 'Invitaciones legacy o alternativas para incorporar miembros al equipo.';
COMMENT ON TABLE public.wp_user_engagement IS 'Eventos granulares de uso de producto por usuario y empresa.';
COMMENT ON TABLE public.wp_user_engagement_daily IS 'Resumen diario de engagement de usuarios por empresa.';
