-- ============================================================================
-- DEEP RESEARCH PERSISTENCE SCHEMA
-- ============================================================================
-- Allows long-running research jobs to persist across sessions.
-- Architecture:
-- - Jobs are created when user starts a research
-- - Firecrawl processes the job asynchronously
-- - Webhook endpoint updates this table when job completes
-- - Artifacts and notifications are created server-side
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.wp_deep_research (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    local_job_id TEXT UNIQUE NOT NULL, -- The ID generated by the client store
    user_id UUID NOT NULL,
    empresa_id BIGINT,
    prompt TEXT NOT NULL,
    urls TEXT[],
    schema JSONB,
    
    -- Firecrawl Integration
    firecrawl_job_id TEXT,
    status TEXT NOT NULL DEFAULT 'queued', -- queued, processing, completed, failed
    
    -- Results
    data JSONB,
    artifact_id UUID REFERENCES public.artifacts(id) ON DELETE SET NULL,
    credits_used INTEGER,
    error TEXT,
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- INDICES
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_deep_research_user ON public.wp_deep_research(user_id);
CREATE INDEX IF NOT EXISTS idx_deep_research_status ON public.wp_deep_research(status);
CREATE INDEX IF NOT EXISTS idx_deep_research_local_id ON public.wp_deep_research(local_job_id);
CREATE INDEX IF NOT EXISTS idx_deep_research_firecrawl_id ON public.wp_deep_research(firecrawl_job_id);
CREATE INDEX IF NOT EXISTS idx_deep_research_empresa ON public.wp_deep_research(empresa_id);

-- ============================================================================
-- RLS POLICIES
-- ============================================================================
-- Note: Service role (used by API routes/webhooks) bypasses RLS
-- These policies are for direct client access (if ever enabled)
ALTER TABLE public.wp_deep_research ENABLE ROW LEVEL SECURITY;

-- Users can view their own research
CREATE POLICY "deep_research_select_own" 
ON public.wp_deep_research FOR SELECT 
USING (auth.uid() = user_id);

-- Users can insert their own research
CREATE POLICY "deep_research_insert_own" 
ON public.wp_deep_research FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Users can update their own research
CREATE POLICY "deep_research_update_own" 
ON public.wp_deep_research FOR UPDATE 
USING (auth.uid() = user_id);

-- ============================================================================
-- TRIGGERS
-- ============================================================================
CREATE OR REPLACE FUNCTION update_deep_research_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_deep_research_updated_at ON public.wp_deep_research;
CREATE TRIGGER trg_deep_research_updated_at
    BEFORE UPDATE ON public.wp_deep_research
    FOR EACH ROW
    EXECUTE FUNCTION update_deep_research_updated_at();

-- ============================================================================
-- DOCUMENTATION
-- ============================================================================
COMMENT ON TABLE public.wp_deep_research IS 'Almacena el estado y resultados de las investigaciones profundas de Monica AI';
COMMENT ON COLUMN public.wp_deep_research.local_job_id IS 'ID generado por el cliente para tracking local';
COMMENT ON COLUMN public.wp_deep_research.firecrawl_job_id IS 'ID del job en Firecrawl para polling y webhooks';
COMMENT ON COLUMN public.wp_deep_research.artifact_id IS 'FK al artifact generado cuando la investigación se completa';
COMMENT ON COLUMN public.wp_deep_research.status IS 'Estado: queued, processing, completed, failed';
